version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DEBUG=false
      # Add your environment variables here
      # - YANDEX_API_KEY=your_api_key
      # - YANDEX_FOLDER_ID=your_folder_id
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - .env:/app/.env:ro  # Mount .env file as read-only 